//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copy
    {
        public long ID { get; set; }
        public long EditionID { get; set; }
        public Nullable<long> PatronID { get; set; }
        public Nullable<System.DateTime> CheckedOut { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Edition Edition { get; set; }
        public virtual Patron Patron { get; set; }
        public virtual DeletedCopy DeletedCopy { get; set; }
    }
}
