//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Edition()
        {
            this.Copies = new HashSet<Copy>();
        }
    
        public long ID { get; set; }
        public long ItemID { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> LU_CoverType { get; set; }
        public Nullable<int> Copyright { get; set; }
        public Nullable<long> PublisherID { get; set; }
        public System.DateTime Added { get; set; }
        public Nullable<int> LU_Language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Copy> Copies { get; set; }
        public virtual Item Item { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
