//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Copy> Copies { get; set; }
        public virtual DbSet<DeletedCopy> DeletedCopies { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<ImmediateReprint> ImmediateReprints { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemSubject> ItemSubjects { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<NewID> NewIDs { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Reprint> Reprints { get; set; }
        public virtual DbSet<Reserve> Reserves { get; set; }
        public virtual DbSet<SpineID> SpineIDs { get; set; }
    }
}
